apiVersion: v1
kind: ConfigMap
metadata:
  name: devdrill-api-cm
  namespace: devdrill-prod
  labels:
    app: devdrill
    tier: api
    env: prod
data:
  NODE_ENV: production
  PORT: 3000

  FILE_BATH_URL: https://devdrill-api.hyeonwoo.com
  FILE_PUBLIC_STORAGE: /app/data/public
