apiVersion: v1
kind: Service
metadata:
  name: devdrill-api
  namespace: devdrill-prod
  labels:
    app: devdrill
    tier: api
    env: prod
spec:
  selector:
    app: devdrill
    tier: api
    env: prod
  ports:
    - port: 3010
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
